# Changes here will be overwritten by Copier; used by `copier update`.
_commit: v0.1.0
_src_path: C:/redberry/src/python/redberry-webapp-template
app_name: Candle Graph
app_slug: candle_graph
github_owner: daniloreddy
