services:
  candle-graph:
    image: ghcr.io/daniloreddy/candle_graph:latest
    container_name: candle-graph
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
